import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { ModalLogin } from "@/components/modal-login";
import { buttonVariants } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kesatria Kode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="px-4 lg:px-6 h-14 flex items-center justify-between gap-3">
          <Link
            href="/"
            className="flex items-center justify-center"
            prefetch={false}
          >
            <CodeIcon className="h-6 w-6" />
            <span className="pl-4 sr-only">Kesatria Kode</span>
          </Link>
          <div className="relative w-full max-w-xs">
            <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <Input
              type="search"
              placeholder="Apa yang ingin anda pelajari"
              className="pl-10 pr-4 py-2 rounded-md bg-background border border-input focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary-foreground w-full"
            />
          </div>
          <div className="flex flex-row justify-center items-center">
            <nav className="ml-auto flex gap-4 sm:gap-6 px-8">
              <Link
                href="/about"
                className="text-sm font-medium hover:underline underline-offset-4"
                prefetch={false}
              >
                About
              </Link>
              <Link
                href="/learning-path"
                className="text-sm font-medium hover:underline underline-offset-4"
                prefetch={false}
              >
                Learning Path
              </Link>
              <Link
                href="/instructor"
                className="text-sm font-medium hover:underline underline-offset-4"
                prefetch={false}
              >
                Instructors
              </Link>
            </nav>
            <div className="flex flex-row gap-3">
              <ModalLogin />
              <Link href={"/register"} className={buttonVariants()}>
                Daftar
              </Link>
            </div>
          </div>
        </header>

        {children}
        <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
          <p className="text-xs text-muted-foreground">
            &copy; 2024 Kesatria Kode. All rights reserved.
          </p>
          <nav className="sm:ml-auto flex gap-4 sm:gap-6">
            <Link
              href="#"
              className="text-xs hover:underline underline-offset-4"
              prefetch={false}
            >
              Facebook
            </Link>
            <Link
              href="#"
              className="text-xs hover:underline underline-offset-4"
              prefetch={false}
            >
              Twitter
            </Link>
            <Link
              href="#"
              className="text-xs hover:underline underline-offset-4"
              prefetch={false}
            >
              Instagram
            </Link>
            <Link
              href="#"
              className="text-xs hover:underline underline-offset-4"
              prefetch={false}
            >
              LinkedIn
            </Link>
          </nav>
        </footer>
      </body>
    </html>
  );
}

function CodeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}

function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
