import Image from "next/image";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iLuCbZnxxAk
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 sm:py-24 lg:py-32 bg-[#f5f5f5]">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Buka Potensi Coding Anda bersama Kesatria Kode
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Rasakan pengalaman bootcamp coding intensif yang mengubah
                    para calon pengembang menjadi profesional siap bersaing di
                    industri.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Bergabung Sekarang
                  </Link>
                </div>
              </div>
              <Image
                src="/images/online-assignment.jpg"
                width="550"
                height="550"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                  Kesatria Kode Bootcamp
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Kurikulum yang Dirancang untuk Sukses
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Kurikulum komprehensif kami mencakup teknologi terbaru dan
                  praktik terbaik industri, memastikan Anda dilengkapi dengan
                  keterampilan yang dibutuhkan oleh para pemberi kerja.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <Image
                src="/images/work-net.jpg"
                width="550"
                height="310"
                alt="Curriculum"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Hands-on Learning</h3>
                      <p className="text-muted-foreground">
                        Dive into practical coding projects and build real-world
                        applications.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Expert Instruction</h3>
                      <p className="text-muted-foreground">
                        Learn from industry-leading instructors with years of
                        experience.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Career Preparation</h3>
                      <p className="text-muted-foreground">
                        Receive guidance on job search strategies and interview
                        skills.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#f5f5f5]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                  Meet Our Instructors
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Experts Dedicated to Your Success
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Our team of seasoned developers and industry professionals are
                  passionate about empowering the next generation of coders.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="flex flex-col items-center justify-center space-y-4 text-center">
                <Image
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Instructor"
                  className="rounded-full"
                />
                <div className="space-y-1">
                  <h3 className="text-xl font-bold">Jouska Brillian</h3>
                  <p className="text-muted-foreground">Lead Instructor</p>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center space-y-4 text-center">
                <Image
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Instructor"
                  className="rounded-full"
                />
                <div className="space-y-1">
                  <h3 className="text-xl font-bold">Faisal Wiratek</h3>
                  <p className="text-muted-foreground">Senior Instructor</p>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center space-y-4 text-center">
                <Image
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Instructor"
                  className="rounded-full"
                />
                <div className="space-y-1">
                  <h3 className="text-xl font-bold">Michael Johnson</h3>
                  <p className="text-muted-foreground">Instructor</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                  Student Testimonials
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Hear from Our Graduates
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Our students have gone on to secure rewarding careers at top
                  tech companies. Hear their stories of transformation.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col items-start space-y-4 bg-[#f5f5f5] p-6 rounded-lg">
                <div className="space-y-2">
                  <p className="text-xl font-bold">
                    &quot;Kesatria Kode changed my life.&quot;
                  </p>
                  <p className="text-muted-foreground">
                    &quot;The hands-on projects and expert instruction at
                    Kesatria\n Kode gave me the skills and confidence to land my
                    dream\n job as a software engineer.&quot;
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <Image
                    src="/placeholder.svg"
                    width="48"
                    height="48"
                    alt="Student"
                    className="rounded-full"
                  />
                  <div>
                    <p className="text-sm font-medium">Emily Chen</p>
                    <p className="text-xs text-muted-foreground">
                      Software Engineer, Acme Inc.
                    </p>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-start space-y-4 bg-[#f5f5f5] p-6 rounded-lg">
                <div className="space-y-2">
                  <p className="text-xl font-bold">
                    &quot;Kesatria Kode is the best decision I ever made.&quot;
                  </p>
                  <p className="text-muted-foreground">
                    &quot;The curriculum at Kesatria Kode is cutting-edge and\n
                    practical. I was able to build a strong portfolio and\n land
                    a job at a top tech company.&quot;
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <Image
                    src="/placeholder.svg"
                    width="48"
                    height="48"
                    alt="Student"
                    className="rounded-full"
                  />
                  <div>
                    <p className="text-sm font-medium">David Lee</p>
                    <p className="text-xs text-muted-foreground">
                      Software Developer, Mega Corp.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#f5f5f5]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                  Join Kesatria Kode
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Take the First Step Towards Your Coding Career
                </h2>
                <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Enroll in our intensive coding bootcamp and unlock your full
                  potential as a developer.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form className="flex gap-2">
                  <Input
                    type="email"
                    placeholder="Enter your email"
                    className="max-w-lg flex-1"
                  />
                  <Button type="submit">Join Now</Button>
                </form>
                <p className="text-xs text-muted-foreground">
                  By signing up, you agree to our{" "}
                  <Link
                    href="#"
                    className="underline underline-offset-2"
                    prefetch={false}
                  >
                    Terms &amp; Conditions
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
