/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q1I7y5nlRj2
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Dialog, DialogTrigger, DialogContent } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import Link from "next/link";

export function ModalLogin() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Masuk</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[500px]">
        <div className="flex flex-col items-center gap-6 p-6">
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" placeholder="m@example.com" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input id="password" type="password" />
            </div>
            <Button type="submit" className="w-full">
              Masuk
            </Button>
            <Button variant="outline" className="w-full">
              <ChromeIcon className="mr-2 h-4 w-4" />
              Masuk dengan Google
            </Button>
            <div className="text-center text-sm text-muted-foreground">
              <Link
                href="#"
                className="underline underline-offset-2"
                prefetch={false}
              >
                Lupa Password?
              </Link>
            </div>
            <div className="text-center text-sm text-muted-foreground">
              Belum punya akun?{" "}
              <Link
                href="#"
                className="underline underline-offset-2"
                prefetch={false}
              >
                Ayo daftar
              </Link>
            </div>
            <div className="text-center text-xs text-muted-foreground">
              Dengan melakukan login, Anda setuju dengan syarat & ketentuan
              Dicoding. This site is protected by reCAPTCHA and the Google
              Privacy Policy and Terms of Service apply.
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function ChromeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  );
}
